// Generated by CodiumAI

import { convertImageToWebp } from "../utils/imageToWebp";
import fs from "fs";
import { promisify } from "util";

const unlink = promisify(fs.unlink);

describe("convertImageToWebp", () => {
  const inputPath = "/public/Image.png";
  const outputPath = "/public/CHANGEDIMAGE.webp";

  afterEach(async () => {
    // Clean up the output file after each test
    try {
      await unlink(outputPath);
    } catch (error) {
      // Ignore error if the file doesn't exist
    }
  });

  it("should convert the image to webp format", async () => {
    const result = await convertImageToWebp(inputPath, outputPath);

    // Assert that the output file exists
    expect(fs.existsSync(outputPath)).toBe(true);

    // Assert that the result is a Buffer
    expect(result).toBeInstanceOf(Buffer);
  });

  it("should throw an error if conversion fails", async () => {
    // Provide an invalid input path to force conversion failure
    const invalidInputPath = "/path/to/invalid/image.jpg";

    await expect(
      convertImageToWebp(invalidInputPath, outputPath)
    ).rejects.toThrow();
  });
});
